### ISSUE TITLE
Newer firmware?

### ISSUE THREAD

**Issue by ariankordi** [damnnfo/ms2130-firmware#2]
Hi there, I found this BiliBili video about a new firmware that might support 4K output: https://www.bilibili.com/video/BV1Lc411V7BU/
Here's the link to it on Weiyun: https://share.weiyun.com/7c1F5a35
I don't know how new it is, because Weiyun doesn't give a preview of RARs, and I can't download it because I'm not Chinese and don't have a WeChat account.
It would be awesome if you could upload this firmware to the repo for everyone. Thanks!

**Comment by damnnfo** [comment]
hi,
Just uploaded 4K firmware.
But they're not tested, so use it at your own risk.
I heard that it may brick the device. (the file size is smaller than the normal one)

**Comment by ariankordi** [comment]
Awesome, thanks!
